import { randomUUID } from "node:crypto";
import request from "supertest";
import { afterAll, describe, expect, it } from "vitest";
import { app } from "../../src/app.js";
import { prisma } from "../../src/config/database.js";

const agent = request.agent(app); const suffix = randomUUID(); let userId; let accountId; let categoryId;
async function cleanup() { if (!userId) return; await prisma.$transaction([prisma.transaction.deleteMany({ where: { userId } }), prisma.subscription.deleteMany({ where: { userId } }), prisma.recurringTransaction.deleteMany({ where: { userId } }), prisma.cardInstallment.deleteMany({ where: { userId } }), prisma.cardPurchase.deleteMany({ where: { userId } }), prisma.creditCardInvoice.deleteMany({ where: { userId } }), prisma.creditCard.deleteMany({ where: { userId } }), prisma.transfer.deleteMany({ where: { userId } }), prisma.subcategory.deleteMany({ where: { userId } }), prisma.category.deleteMany({ where: { userId } }), prisma.account.deleteMany({ where: { userId } }), prisma.user.delete({ where: { id: userId } })]); }
describe.sequential("recorrências e assinaturas", () => {
  afterAll(async () => { await cleanup(); await prisma.$disconnect(); });
  it("cria base de dados do usuário", async () => { const register = await agent.post("/api/auth/register").send({ name: "Planejador", email: `planejamento-${suffix}@example.test`, password: "SenhaSegura123", currency: "BRL" }); expect(register.status).toBe(201); userId = register.body.user.id; const account = await agent.post("/api/accounts").send({ name: "Conta fixa", type: "CHECKING", initialBalance: "0" }); accountId = account.body.account.id; const categories = await agent.get("/api/categories?type=EXPENSE&status=active"); categoryId = categories.body.categories.find((item) => item.name === "Internet").id; });
  it("gera ocorrências sem duplicá-las", async () => { const recurring = await agent.post("/api/recurrences").send({ accountId, categoryId, type: "EXPENSE", description: "Internet residencial", amount: "100", frequency: "MONTHLY", startDate: "2026-08-01" }); expect(recurring.status).toBe(201); const first = await agent.post("/api/recurrences/generate").send({ through: "2026-10-02" }); expect(first.status).toBe(200); expect(first.body.generated).toBe(3); const second = await agent.post("/api/recurrences/generate").send({ through: "2026-10-02" }); expect(second.body.generated).toBe(0); const transactions = await agent.get("/api/transactions?limit=10"); expect(transactions.body.transactions).toHaveLength(3); expect(transactions.body.transactions.every((item) => item.status === "PENDING")).toBe(true); });
  it("respeita duração e encerramento manual sem apagar o histórico", async () => { const limited = await agent.post("/api/recurrences").send({ accountId, categoryId, type: "EXPENSE", description: "Financiamento", amount: "50", frequency: "MONTHLY", startDate: "2026-08-10", endMode: "DURATION", durationValue: 3, durationUnit: "MONTHS" }); expect(limited.status).toBe(201); expect(limited.body.recurrence.endDate.slice(0, 10)).toBe("2026-11-09"); await agent.post("/api/recurrences/generate").send({ through: "2026-12-31" }); expect(await prisma.transaction.count({ where: { recurringTransactionId: limited.body.recurrence.id } })).toBe(3); const closed = await agent.patch(`/api/recurrences/${limited.body.recurrence.id}`).send({ status: "COMPLETED" }); expect(closed.status).toBe(200); expect(closed.body.recurrence.endedAt).toBeTruthy(); await agent.post("/api/recurrences/generate").send({ through: "2027-12-31" }); expect(await prisma.transaction.count({ where: { recurringTransactionId: limited.body.recurrence.id } })).toBe(3); });
  it("calcula equivalência mensal de assinaturas localmente", async () => { const subscription = await agent.post("/api/subscriptions").send({ serviceName: "Streaming semanal", categoryId, accountId, amount: "12", frequency: "WEEKLY", nextBillingDate: "2026-08-15" }); expect(subscription.status).toBe(201); const listed = await agent.get("/api/subscriptions"); expect(listed.status).toBe(200); expect(listed.body.subscriptions[0].monthlyEquivalent).toBe("52"); expect(listed.body.monthlyTotal).toBe("52"); });
});
