import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { dashboardService } from '../services/dashboard.service.js'
import { formatCurrency } from '../utils/formatters.js'
import { getApiError } from '../utils/get-api-error.js'
import { useAuth } from '../hooks/useAuth.js'

export function HomePage() {
  const { user } = useAuth(); const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [state, setState] = useState({ loading: true, error: '', data: null })
  useEffect(() => { let active = true; dashboardService.get(month).then((data) => active && setState({ loading: false, error: '', data })).catch((error) => active && setState({ loading: false, error: getApiError(error), data: null })); return () => { active = false } }, [month])
  const data = state.data; const max = data ? Math.max(...data.monthlySeries.flatMap((item) => [Number(item.income), Number(item.expense)]), 1) : 1
  const hasOverdue = Number(data?.summary.overdueBills) > 0
  const hasPending = Number(data?.summary.pendingBills) > 0
  return <section className="page-stack"><div className="page-heading with-action"><div><p className="eyebrow">Fase 6 · Visão geral</p><h1>Olá, {user.name.split(' ')[0]}.</h1><p>Seu resumo financeiro atualizado.</p></div><label className="month-picker"><span>Período</span><input type="month" value={month} onChange={(event) => setMonth(event.target.value)} /></label></div>{state.error ? <div className="form-alert">{state.error}</div> : null}{state.loading ? <p className="loading-inline">Carregando painel...</p> : null}{data ? <><section className="overview-grid"><article className="overview-card overview-card-primary"><span>Saldo disponível projetado</span><strong>{formatCurrency(data.summary.availableBalance, user.currency)}</strong><small>Saldo real: {formatCurrency(data.summary.currentBalance, user.currency)}</small></article><article className="overview-card"><span>Resultado mensal</span><strong>{formatCurrency(data.summary.monthlyResult, user.currency)}</strong><small>Receitas menos despesas</small></article></section><section className="metric-grid"><article><span>Receitas</span><strong className="income-text">{formatCurrency(data.summary.monthlyIncome, user.currency)}</strong></article><article><span>Despesas</span><strong className="expense-text">{formatCurrency(data.summary.monthlyExpense, user.currency)}</strong></article><article className={hasOverdue ? 'metric-alert is-overdue' : hasPending ? 'metric-alert' : ''}><span>A pagar</span><strong>{formatCurrency(data.summary.pendingBills, user.currency)}</strong><small>{hasOverdue ? `Atrasado: ${formatCurrency(data.summary.overdueBills, user.currency)}` : hasPending ? 'Existem compromissos pendentes' : 'Sem contas pendentes'}</small></article><article><span>Cartões</span><strong>{formatCurrency(data.summary.totalCardUsed, user.currency)}</strong><small>Faturas em aberto</small></article></section><section className="dashboard-panel"><p className="eyebrow">Fluxo</p><h2>Receitas x despesas</h2><div className="bar-chart">{data.monthlySeries.map((item) => <div className="bar-group" key={item.label}><div className="bars"><i className="bar-income" style={{ height: `${Number(item.income) / max * 100}%` }} /><i className="bar-expense" style={{ height: `${Number(item.expense) / max * 100}%` }} /></div><small>{item.label}</small></div>)}</div></section><section className="setup-card"><div><p className="eyebrow">Ações rápidas</p><h2>Organize o próximo lançamento.</h2></div><div className="setup-actions"><Link className="primary-button inline-button" to="/movimentacoes">Novo lançamento</Link><Link className="secondary-button inline-button" to="/cartoes">Ver cartões</Link></div></section></> : null}</section>
}
